name: sigl_prep
channels:
  - defaults
  - conda-forge
  - bioconda
  - r
  - cran

dependencies:
  - sra-tools=2.9.1
  - star=2.6.1a
  - samtools=1.9
  - fastqc
  - multiqc
  - kallisto
  - python=3.6.5
  - numpy==1.18.1
  - pandas
  - scipy==1.4.1
  - pysam==0.15.4
  - matplotlib
  - seaborn
  - R
  - bioconductor-DRIMSeq
  - bioconductor-deseq2
  - bioconductor-tximport
  - bioconductor-ensembldb
  - bioconductor-EnsDb.Hsapiens.v86
  - bioconductor-rhdf5
  - bioconductor-limma
  - r-optparse
  - r-uwot
  - r-ggplot2
  - r-RColorBrewer
  - r-pheatmap
  - r-tidyverse
  - r-doParallel
  - r-foreach
