name: sigl_prep
channels:
  - defaults
  - conda-forge
  - bioconda
  - r
  - cran

dependencies:
  - sra-tools=2.9.1
  - star=2.6.1a
  - samtools=1.9
  - fastqc
  - multiqc
  - kallisto
  - R
  - bioconductor-deseq2
  - bioconductor-tximportData
  - bioconductor-tximport
  - bioconductor-ensembldb
  - bioconductor-EnsDb.Hsapiens.v86
  - bioconductor-rhdf5
  - r-optparse
  - r-uwot
  - r-ggplot2
  - r-RColorBrewer
